### ISSUE TITLE
Unable to Authenticate using Wiki-recommended instructions

### ISSUE THREAD

**Issue by joshuaballoch** [Mangopay/mangopay2-ruby-sdk#79]
On the main Wiki page here: https://github.com/Mangopay/mangopay2-ruby-sdk/wiki

The recommended way of configuring MangoPay in an application is to run the command:

`rails generate mangopay:install CLIENT_ID CLIENT_NAME`

This yields an error: `No value provided for required arguments 'client_email'`

So I presume I just add a third argument:

`rails generate mangopay:install CLIENT_ID CLIENT_NAME CLIENT_EMAIL`

This also yields an error:

`NoMethodError: undefined method `create' for MangoPay::Client:Class`

I assume this is either outdated documentation or the gem has a bug in it

**Comment by adrien-thebault** [comment]
Same problem here, Client.create was removed in [this commit](https://github.com/Mangopay/mangopay2-ruby-sdk/commit/cb09f62179d199bcb988cd0e1f1f577233accac5), but the generator has not been adapted accordingly

**Comment by mickaelpois** [comment]
Dear @joshuaballoch and @adrien-thebault,
This issue will be analysed on the next couple of weeks, sorry for this painful and long wait.
I will keep you posted with any good news regarding this issue.

Mickaël

**Comment by paulhristea** [comment]
As far as I can tell, Clients can no longer be created through the API directly, either because of that feature having been a temporary shortcut for test development, or due to some ulterior authentication flow restructuring. Please confirm.

Anyway, the Wiki page hasn't been updated for a few years, but I think it should now mention that the client passphrase can be acquired from the registration process at https://www.mangopay.com/signup/sandbox/ , after which the Mangopay.configure method can be called with the registration data.

Will look into this further and update docs accordingly.

**Comment by hobailey** [comment]
That's absolutely right - we've made quite a few changes to how new accounts are created, and indeed it's no longer possible to just do it from the command line so simply. I've updated the Wiki to avoid confusion on this point - thanks for bringing it up.
